---
official_packages:
  # System ------------------------------------------------------------------------------------------
  - bluez                                         # Bluetooth support
  - hunspell                                      # Spellchecking and the english dictionary
  - hunspell-en_US
  - kvantum-qt5                                   # SVG theme engine for KDE
  - lshw                                          # To list the hardware
  - xclip                                         # Clipboard manager for the command line
  - xdotool                                       # Send key presses via terminal
  - wmctrl                                        # Control the window manager via CLI
  - lshw                                          # Hardware configuration info
  - hwinfo                                        # Hardware general info
  - keychain                                      # Handle ssh-agent
  - bluedevil                                     # Bluetooth support for KDE
  - qt5-imageformats                              # Thumbnails for other image formats, like WEBP
  - kio-extras                                    # Additional functionality for KIO
  - ffmpegthumbs                                  # Thumbnails for video formats
  - sheldon                                       # Shell plugin manager

  # Base ------------------------------------------------------------------------------------------------------
  - exa                                           # A better ls
  - neovim                                        # The only vim
  - ranger                                        # Terminal file explorer
  - trash-cli                                     # Send files to the DE trash bin instead of obliterating them
  - rofi                                          # Highly customizable application launcher
  - zoxide                                        # Z auto-jumping
  - wireshark-qt                                  # Network traffic monitoring like a hacker
  - glow                                          # TUI markdown viewer
  - pigz                                          # Parallel GZip
  - lbzip2                                        # Parallel BZip2

  # Development -------------------------------------------------------------------------------
  - docker                                        # Containerize all the things
  - docker-compose
  - github-cli                                    # Finer access to GitHub features
  - jre-openjdk                                   # Run Java apps
  - jdk-openjdk
  - python                                        # Python and its package manager
  - python-pip
  - git-delta                                     # Next-Gen Diff engine
  - shellcheck                                    # Syntax and checker for shellscript
  - gpick                                         # Super advanced color picker
  - dbeaver                                       # GUI to manage DBMS
  - git-lfs                                       # Really large files support for Git, like your momma
  - gource                                        # Git history visualization
  - kubectl                                       # Container hell management
  - lazygit                                       # Git TUI
  - go                                            # Go core compiler tools
  - rustup                                        # Rust management tool

  # Utils -----------------------------------------------------------------------------------------------------------
  - mpv                                           # The best universal media player
  - qbittorrent                                   # My preferred torrent client
  - thunderbird                                   # Email client
  - libreoffice-fresh                             # Because everyone needs to edit documents (fresh = latest version)
  - chromium                                      # A chromium engine is needed more times that you may think
  - jq                                            # A terminal JSON formatter
  - fzf                                           # Fuzzy finder for any list
  - btop                                          # A more advanced htop
  - krita                                         # Digital drawing software
  - inkscape                                      # Vector image editor
  - sd                                            # A faster replacement for sed
  - dua                                           # Disk usage visualizer
  - atool                                         # Manage file archives of various types

  # Gaming ----------------------------------------------------------------------------------
  - vulkan-icd-loader                             # Vulkan libs required by some games
  - lib32-vulkan-icd-loader
  - steam                                         # One-stop game shop
  - lutris                                        # For when one-stop is actually two-stops
  - discord                                       # Communication at its finest

  # Fonts -----------------------------------------------------------------------------------------------
  - ttf-roboto                                    # Roboto, a beautiful Google font
  - noto-fonts-emoji                              # OpenSource emoji font, because we like emojis, right?

  # Misc --------------------------------------------------------------------------------------
  - cowsay                                        # Because just printing to terminal is boring
  - fortune-mod                                   # And to have something for cows to say
  - onefetch                                      # Visualize repository infos in a cool way
  - lolcat                                        # Rainbow terminal

aur_packages:
  # System ----------------------------------------------------------------------------------------------------------
  - bluez-utils-compat                             # More bluetooth support
  - hunspell-pt-br                                 # Portuguese spellcheck
  - epson-inkjet-printer-escpr                     # EPSON printer drivers
  - input-wacom-dkms                               # Wacom tablet driver
  - ventoy-bin                                     # Multi ISO USB manager
  - kwallet-secrets                                # KDE secrets management with support for org.freedesktop.secrets

  # Base ------------------------------------------------------------------------------------------------------------
  - google-chrome                                  # Chrome with sync
  - google-chrome-dev                              # Chrome latest features
  - firefox-developer-edition                      # My to-go browser, with lots of feature for developers
  - bat                                            # Cat but with syntax highlighting
  - tealdeer                                       # Tldr provides example usages for some commands
  - qalculate-qt5                                  # The best calculator in existence
  - tdrop                                          # Transform any application into a dropdown window
  - 7-zip-full                                     # Official full replacement for p7zip

  # Utils ---------------------------------------------------------------------------------------------
  - teams-insiders                                 # Because unfortunately, discord isn't enough
  - spotify                                        # Let's dance, baby
  - quiterss                                       # One of the best RSS feed readers
  - stretchly-bin                                  # Take frequent breaks
  - gallery-dl-bin                                 # CLI image downloader for various sources
  - ookla-speedtest-bin                            # Speedtest.net CLI
  - 1password                                      # My favorite password manager
  - tere                                           # Navigate folders like a pro
  - cheat                                          # Vizualize cheatsheets on the terminal

  # Communication ---------------------------------------------------------------
  - discord-ptb                                    # Double profile for discord

  # Development ---------------------------------------------------------------------------------------------------
  - visual-studio-code-bin                         # Proprietary VSCode, because we need things to work
  - jetbrains-toolbox                              # Installs any JetBrains related product with one authentication
  - insomnia-bin                                   # REST API designing and testing workspace
  - gitgudcli-bin                                  # GitGud CLI wrapper
  - gibo                                           # Github's gitignore collection from the CLI
  - lazydocker-bin                                 # Docker TUI
  - aws-cli-v2-bin                                 # AWS management, because managing your own infra is hard (and you don't really care about money, do you ?)
  - pnpm                                           # A better and more disk efficient NPM, because disk space if expensive
  - nvm                                            # Node Version Manager, because having just one circle of hell isn't enough
  - kubecolor                                      # Colorize kubectl output
  - hexyl                                          # Hex vizualizer for the CLI
  - hyperfine                                      # Benchmark CLI execution times

  # Gaming ------------------------------------------------------------------------------------
  - ds4drv-cemuhook-git                            # DualShock 4 drivers with CemuHook support
  - multimc-bin                                    # Minecraft multi instance launcher
  - citra-qt-bin                                   # 3DS emulator, because I like Pokemon
  - yuzu-mainline-bin                              # Switch emulator, because (I like Pokemon)Â² and Zelda
  - vintagestory                                   # Minecraft survival on steroids

  # Fonts -------------------------------------------------------------
  - nerd-fonts-fira-code                           # FiraCode Nerd Font

  # Misc --------------------------------------------------------------------------
  - shell-color-scripts                            # Visualize shell colors
  - img2xterm                                      # Display images on the terminal
  - pokemonsay-newgenerations-git                  # Cowsay with pokemon
  - mpv-mpris                                      # Enable MPRIS for MPV
  - wakatime-cli-bin                               # WakaTime CLI
  - fastfetch-git                                  # Visualize distro infos in a cool way
